name: tag-release-publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tag-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Tag & release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: gh-actions-publish-test-abc-123

      - uses: actions/checkout@v4

      - name: Publish to NPM
        uses: ./.github/actions/publish
        # The if statement ensures that a publication only occurs when
        # a new release is created from the release step above, i.e. the
        # release PR has been merged.
        if: ${{ steps.release.outputs.release_created }}
