name: tag-release-publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Tag & release
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: gh-actions-publish-test-abc-123

      # Publish to NPM
      - uses: actions/checkout@v4
        # The if statements ensure that a publication only occurs when
        # a new release is created from the release step above, i.e. the
        # release PR has been merged.
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version-file: .nvmrc
          cache: npm
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
