name: Version Minor Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump the minor version
        uses: ./.github/actions/bump-version
        with:
          type: "minor"
