name: Version Patch Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump the patch version
        uses: ./.github/actions/bump-version
        with:
          type: "patch"
